"""empty message

Revision ID: 3c7a6bf3c5f0
Revises: 3fde143bbe4a
Create Date: 2014-08-18 19:53:39.420000

"""

# revision identifiers, used by Alembic.
revision = '3c7a6bf3c5f0'
down_revision = '3fde143bbe4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    ### end Alembic commands ###
