"""empty message

Revision ID: 3fde143bbe4a
Revises: 14db1589836f
Create Date: 2014-08-08 01:18:33.153000

"""

# revision identifiers, used by Alembic.
revision = '3fde143bbe4a'
down_revision = '14db1589836f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', sa.String(length=15), nullable=True))
    op.drop_column('user', 'phone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('user', 'mobile')
    ### end Alembic commands ###
